services:
  postgres:
    image: 'postgres:16-alpine'
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_DB=autoparts_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data: